package com.ey.application.view;

import java.awt.Color;
import java.awt.Frame;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.beans.PropertyVetoException;
import java.io.BufferedWriter;
import java.io.FileWriter;
import java.io.IOException;
import java.text.SimpleDateFormat;
import java.util.Date;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Fuizzal
 */
public class frmPrintReport extends javax.swing.JInternalFrame {

	/**
	 * Creates new form jfmPrintReport
	 */
	public frmPrintReport() {
		initComponents();
	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
	// <editor-fold defaultstate="collapsed" desc="Generated Code">
	private void initComponents() {

		this.setIconifiable(true);
		this.setMaximizable(false);
		this.setClosable(true);
		this.getContentPane().setBackground(new Color(210, 220, 255));
		this.setResizable(false);
		this.setTitle("帳票印刷");
		jPanel1 = new javax.swing.JPanel();
		jButton1 = new javax.swing.JLabel();
		jTextField1 = new javax.swing.JTextField();
		jTextField2 = new javax.swing.JTextField();
		jPanel2 = new javax.swing.JPanel();
		jButton2 = new javax.swing.JLabel();
		jComboBox1 = new javax.swing.JComboBox<>();
		jPanel3 = new javax.swing.JPanel();
		jButton3 = new javax.swing.JButton();
		jButton4 = new javax.swing.JButton();
		jPanel4 = new javax.swing.JPanel();
		jButton5 = new javax.swing.JButton();

		// setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
		// setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
		// setEnabled(false);

		jButton1.setText("決算年月");

		jTextField1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
		//jTextField1.setText("2010");
		jTextField1.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));

		jTextField2.setHorizontalAlignment(javax.swing.JTextField.CENTER);
		//jTextField2.setText("3");
		SimpleDateFormat formatMon = new SimpleDateFormat("MM");
		SimpleDateFormat formatYear = new SimpleDateFormat("yyyy");
		Date date = new Date();
		
		String mon = String.valueOf(formatMon.format(date));
		String year =  String.valueOf(formatYear.format(date));
		
		setMonthYear(mon, year);
		jTextField1.setText(rptYear);
		jTextField2.setText(rptMon);
		
		javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
		jPanel1.setLayout(jPanel1Layout);
		jPanel1.setBackground(new Color(210, 220, 255));
		jPanel2.setBackground(new Color(210, 220, 255));
		jPanel3.setBackground(new Color(210, 220, 255));
		jPanel4.setBackground(new Color(210, 220, 255));
		jPanel1Layout.setHorizontalGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(jPanel1Layout.createSequentialGroup().addContainerGap()
						.addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 50,
								javax.swing.GroupLayout.PREFERRED_SIZE)
						.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED).addComponent(jTextField2)
						.addContainerGap())
				.addGroup(jPanel1Layout.createSequentialGroup().addGap(25, 25, 25).addComponent(jButton1)
						.addContainerGap(25, Short.MAX_VALUE))

		);
		jPanel1Layout.setVerticalGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(jPanel1Layout.createSequentialGroup().addContainerGap().addComponent(jButton1)
						.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
						.addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
								.addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE,
										javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
								.addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE,
										javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
						.addContainerGap(13, Short.MAX_VALUE)));

		jButton2.setText("範囲");
		
		//jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "すべて" }));
		jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "すべて","少額資産除く" }));

		javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
		jPanel2.setLayout(jPanel2Layout);
		jPanel2Layout.setHorizontalGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(jPanel2Layout.createSequentialGroup().addComponent(jButton2)
						.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
						.addComponent(jComboBox1, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
						.addGap(12, 12, 12)));
		jPanel2Layout.setVerticalGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
						.addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
						.addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
								.addComponent(jButton2).addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE,
										javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
						.addContainerGap()));

		jButton3.setText("備品台帳 兼 償却計算表");
		jButton3.addActionListener(new ActionListener() {
			public void actionPerformed(ActionEvent e) {
				String y = jTextField1.getText();
				String m = jTextField2.getText();
				String r = String.valueOf(jComboBox1.getSelectedIndex());
				setMonthYear(m, y);
				WriteReportParam(rptMon,rptYear,r);
				JasperReportFill nw = JasperReportFill.getInstance();
				nw.pack();
				if (nw.isVisible()) {
				} else {
					getDesktopPane().add(nw);
					nw.setVisible(true);
				}
				nw.setIconifiable(true);
				nw.setMaximizable(false);
				nw.setClosable(true);
				
				try {
					nw.setMaximum(true);
				} catch (PropertyVetoException e1) {
					// TODO Auto-generated catch block
					e1.printStackTrace();
				}

				dispose();
			}
		});

		jButton4.setText("固定資産ラベル");
		jButton4.addActionListener(new ActionListener() {
			public void actionPerformed(ActionEvent e) {
				frmPrintLabel nw = frmPrintLabel.getInstance();
				nw.pack();
				if (nw.isVisible()) {
				} else {
					getDesktopPane().add(nw);
					nw.setVisible(true);
				}

				nw.setIconifiable(true);
				nw.setMaximizable(false);
				nw.setClosable(true);
				dispose();
			}
		});

		javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
		jPanel3.setLayout(jPanel3Layout);
		jPanel3Layout.setHorizontalGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(jPanel3Layout.createSequentialGroup()
						.addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
								.addComponent(jButton3).addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE,
										149, javax.swing.GroupLayout.PREFERRED_SIZE))
						.addGap(0, 20, Short.MAX_VALUE)));
		jPanel3Layout
				.setVerticalGroup(
						jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
								.addGroup(jPanel3Layout.createSequentialGroup()
										.addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 73,
												javax.swing.GroupLayout.PREFERRED_SIZE)
										.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
										.addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 33,
												javax.swing.GroupLayout.PREFERRED_SIZE)
						.addGap(0, 55, Short.MAX_VALUE)));

		jButton4.getAccessibleContext().setAccessibleName("");

		jButton5.setText("閉じる");
		jButton5.addActionListener(new ActionListener() {
			public void actionPerformed(ActionEvent e) {
				dispose();
			}
		});
		javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
		jPanel4.setLayout(jPanel4Layout);
		jPanel4Layout.setHorizontalGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(jPanel4Layout.createSequentialGroup().addContainerGap()
						.addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 83,
								javax.swing.GroupLayout.PREFERRED_SIZE)
						.addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)));
		jPanel4Layout.setVerticalGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addComponent(jButton5, javax.swing.GroupLayout.DEFAULT_SIZE, 114, Short.MAX_VALUE));

		layout = new javax.swing.GroupLayout(getContentPane());
		getContentPane().setLayout(layout);
		layout.setHorizontalGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addGroup(layout
				.createSequentialGroup().addGap(114, 114, 114)
				.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
						.addGroup(layout.createSequentialGroup()
								.addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE,
										javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
								.addGap(27, 27, 27).addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE,
										javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
						.addGroup(layout.createSequentialGroup()
								.addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE,
										javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
								.addGap(18, 18, 18).addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE,
										javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
				.addContainerGap(89, Short.MAX_VALUE)));
		layout.setVerticalGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(layout.createSequentialGroup().addGap(21, 21, 21)
						.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
								.addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE,
										javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
								.addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE,
										javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
				.addGap(21, 21, 21)
				.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
						.addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE,
								javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
						.addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE,
								javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
				.addContainerGap(18, Short.MAX_VALUE)));

		pack();
	}// </editor-fold>

	/**
	 * @param args
	 *            the command line arguments
	 */
	/*
	 * public static void main(String args[]) { Set the Nimbus look and feel
	 * //<editor-fold defaultstate="collapsed" desc=
	 * " Look and feel setting code (optional) "> If Nimbus (introduced in Java
	 * SE 6) is not available, stay with the default look and feel. For details
	 * see
	 * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
	 * 
	 * try { for (javax.swing.UIManager.LookAndFeelInfo info :
	 * javax.swing.UIManager.getInstalledLookAndFeels()) { if
	 * ("Nimbus".equals(info.getName())) {
	 * javax.swing.UIManager.setLookAndFeel(info.getClassName()); break; } } }
	 * catch (ClassNotFoundException ex) {
	 * java.util.logging.Logger.getLogger(frmPrintReport.class.getName()).log(
	 * java.util.logging.Level.SEVERE, null, ex); } catch
	 * (InstantiationException ex) {
	 * java.util.logging.Logger.getLogger(frmPrintReport.class.getName()).log(
	 * java.util.logging.Level.SEVERE, null, ex); } catch
	 * (IllegalAccessException ex) {
	 * java.util.logging.Logger.getLogger(frmPrintReport.class.getName()).log(
	 * java.util.logging.Level.SEVERE, null, ex); } catch
	 * (javax.swing.UnsupportedLookAndFeelException ex) {
	 * java.util.logging.Logger.getLogger(frmPrintReport.class.getName()).log(
	 * java.util.logging.Level.SEVERE, null, ex); } //</editor-fold>
	 * 
	 * Create and display the form java.awt.EventQueue.invokeLater(new
	 * Runnable() { public void run() { new frmPrintReport().setVisible(true); }
	 * }); }
	 */

	public void WriteReportParam(String m,String y,String r) {
		try {
			String workingDir = System.getProperty("user.dir");
			String sourceFileName = workingDir + "\\rpt\\param.txt";
			// Assume default encoding.
			FileWriter fileWriter;

			fileWriter = new FileWriter(sourceFileName);

			// Always wrap FileWriter in BufferedWriter.
			BufferedWriter bufferedWriter = new BufferedWriter(fileWriter);

			// Note that write() does not automatically
			// append a newline character.
			bufferedWriter.write(m+"=="+y+"=="+r);
			
			// Always close files.
			bufferedWriter.close();
		} catch (IOException e) {
			// TODO Auto-generated catch block
			e.printStackTrace();
		}
	}
	
	public void setMonthYear(String mon, String year)
	{
		int CurrentMonth = Integer.parseInt(mon);
		String CurrentYear =  year;
		
		if(CurrentMonth >=1 && CurrentMonth <=3){
			rptYear = CurrentYear;
			rptMon = "3";
		} else if(CurrentMonth >=4 && CurrentMonth <=6){
			rptYear = CurrentYear;
			rptMon = "6";
		} else if(CurrentMonth >=7 && CurrentMonth <=9){
			rptYear = CurrentYear;
			rptMon = "9";
		} else {
			rptYear = CurrentYear;
			rptMon = "12";
		} 
	}

	// Variables declaration - do not modify
	private javax.swing.JLabel jButton1;
	private javax.swing.JLabel jButton2;
	private javax.swing.JButton jButton3;
	private javax.swing.JButton jButton4;
	private javax.swing.JButton jButton5;
	private javax.swing.JComboBox<String> jComboBox1;
	private javax.swing.JPanel jPanel1;
	private javax.swing.JPanel jPanel2;
	private javax.swing.JPanel jPanel3;
	private javax.swing.JPanel jPanel4;
	private javax.swing.JTextField jTextField1;
	private javax.swing.JTextField jTextField2;
	private javax.swing.GroupLayout layout;
	
	private String rptMon;
	private String rptYear;
	// End of variables declaration

}
