package com.ey.application.view;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.List;
import java.util.Vector;

import javax.swing.JComboBox;
import javax.swing.JOptionPane;
import javax.swing.JTextArea;

import com.ey.application.controller.DBManager;
import com.ey.application.model.FixedAssets;
import com.ey.application.view.frmRegistor.Item;

public class frmPrintLabel extends javax.swing.JInternalFrame {
	

	/**
	 * Creates new form frmPrintLabel
	 */
	public frmPrintLabel() {
		initComponents();
	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
	// <editor-fold defaultstate="collapsed" desc="Generated
	// Code">//GEN-BEGIN:initComponents
	private void initComponents() {

		pnlPanel1 = new javax.swing.JPanel();
		jLabel1 = new javax.swing.JLabel();
		jLabel2 = new javax.swing.JLabel();
		jLabel3 = new javax.swing.JLabel();
		jLabel4 = new javax.swing.JLabel();
		jLabel5 = new javax.swing.JLabel();
		jLabel6 = new javax.swing.JLabel();
		jLabel7 = new javax.swing.JLabel();
		jLabel8 = new javax.swing.JLabel();
		jLabel9 = new javax.swing.JLabel();
		jLabel10 = new javax.swing.JLabel();
		jLabel11 = new javax.swing.JLabel();
		jLabel12 = new javax.swing.JLabel();
		jLabel13 = new javax.swing.JLabel();
		jLabel14 = new javax.swing.JLabel();
		jLabel15 = new javax.swing.JLabel();
		jLabel16 = new javax.swing.JLabel();
		cmdButton1 = new javax.swing.JButton();
		cmdButton2 = new javax.swing.JButton();
		txtField1 = new javax.swing.JTextField();

		this.setTitle("固定資産ラベル");

		jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
		jLabel1.setText("資産名");
		jLabel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

		jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
		jLabel2.setText(".");
		jLabel2.setBorder(javax.swing.BorderFactory.createEtchedBorder());

		jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
		jLabel3.setText("部門名");
		jLabel3.setBorder(javax.swing.BorderFactory.createEtchedBorder());

		jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
		jLabel4.setText(".");
		jLabel4.setBorder(javax.swing.BorderFactory.createEtchedBorder());

		jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
		jLabel5.setText("購入日");
		jLabel5.setBorder(javax.swing.BorderFactory.createEtchedBorder());

		jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
		jLabel6.setText(".");
		jLabel6.setBorder(javax.swing.BorderFactory.createEtchedBorder());

		jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
		jLabel7.setText("資産名");
		jLabel7.setBorder(javax.swing.BorderFactory.createEtchedBorder());

		jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
		jLabel8.setText(".");
		jLabel8.setBorder(javax.swing.BorderFactory.createEtchedBorder());

		jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
		jLabel9.setText("部門名");
		jLabel9.setBorder(javax.swing.BorderFactory.createEtchedBorder());

		jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
		jLabel10.setText(".");
		jLabel10.setBorder(javax.swing.BorderFactory.createEtchedBorder());

		jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
		jLabel11.setText("購入日");
		jLabel11.setBorder(javax.swing.BorderFactory.createEtchedBorder());

		jLabel12.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
		jLabel12.setText(".");
		jLabel12.setBorder(javax.swing.BorderFactory.createEtchedBorder());

		jLabel13.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
		jLabel13.setText("型番");
		jLabel13.setToolTipText("");
		jLabel13.setBorder(javax.swing.BorderFactory.createEtchedBorder());

		jLabel14.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
		jLabel14.setText(".");
		jLabel14.setBorder(javax.swing.BorderFactory.createEtchedBorder());

		jLabel15.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
		jLabel15.setText("連絡先");
		jLabel15.setBorder(javax.swing.BorderFactory.createEtchedBorder());

		jLabel16.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
		jLabel16.setText(".");
		jLabel16.setBorder(javax.swing.BorderFactory.createEtchedBorder());

		cmdButton1.setText("次");
		cmdButton1.setToolTipText("");
		cmdButton1.addActionListener(new ActionListener() {
			public void actionPerformed(ActionEvent e) {
				rowIndex++;
				if(FixedAssets_all.size()-1 == rowIndex)
					cmdButton1.setEnabled(false);
				setGUIText(FixedAssets_all.get(rowIndex));
				if(rowIndex>0)
					cmdButton2.setEnabled(true);
				txtField1.setText((rowIndex+1)+" / "+FixedAssets_all.size());
			}
		});
		

		cmdButton2.setText("前");
		cmdButton2.setEnabled(false);
		cmdButton2.addActionListener(new ActionListener() {
			public void actionPerformed(ActionEvent e) {
				rowIndex--;
				if(rowIndex==0)
					cmdButton2.setEnabled(false);
				setGUIText(FixedAssets_all.get(rowIndex));
				
				
				if(FixedAssets_all.size()-1 > rowIndex)
					cmdButton1.setEnabled(true);
				txtField1.setText((rowIndex+1)+" / "+FixedAssets_all.size());
				
			}
		});
		txtField1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
		

		javax.swing.GroupLayout pnlPanel1Layout = new javax.swing.GroupLayout(pnlPanel1);
		pnlPanel1.setLayout(pnlPanel1Layout);
		pnlPanel1Layout.setHorizontalGroup(pnlPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(pnlPanel1Layout.createSequentialGroup().addContainerGap()
						.addGroup(pnlPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
								.addGroup(pnlPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
										.addComponent(jLabel5, javax.swing.GroupLayout.Alignment.TRAILING,
												javax.swing.GroupLayout.DEFAULT_SIZE,
												javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
								.addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING,
										javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE,
										Short.MAX_VALUE)
								.addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING,
										javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE,
										Short.MAX_VALUE)
								.addComponent(jLabel7, javax.swing.GroupLayout.Alignment.TRAILING,
										javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE,
										Short.MAX_VALUE)
								.addComponent(jLabel11, javax.swing.GroupLayout.DEFAULT_SIZE,
										javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
								.addComponent(jLabel13, javax.swing.GroupLayout.DEFAULT_SIZE,
										javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
								.addComponent(jLabel15, javax.swing.GroupLayout.DEFAULT_SIZE,
										javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE).addComponent(jLabel9,
												javax.swing.GroupLayout.Alignment.TRAILING,
												javax.swing.GroupLayout.DEFAULT_SIZE,
												javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
						.addGroup(pnlPanel1Layout.createSequentialGroup()
								.addComponent(cmdButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 80,
										javax.swing.GroupLayout.PREFERRED_SIZE)
								.addGap(0, 0, 0)))
						.addGroup(pnlPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
								.addGroup(javax.swing.GroupLayout.Alignment.TRAILING,
										pnlPanel1Layout.createSequentialGroup().addGap(10, 10, 10)
												.addComponent(txtField1, javax.swing.GroupLayout.PREFERRED_SIZE, 226,
														javax.swing.GroupLayout.PREFERRED_SIZE)
										.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED,
												javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
										.addComponent(cmdButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 80,
												javax.swing.GroupLayout.PREFERRED_SIZE))
								.addComponent(jLabel16, javax.swing.GroupLayout.DEFAULT_SIZE,
										javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
								.addComponent(jLabel14, javax.swing.GroupLayout.DEFAULT_SIZE,
										javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
								.addComponent(jLabel12, javax.swing.GroupLayout.DEFAULT_SIZE,
										javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
								.addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE,
										javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
								.addComponent(jLabel4, javax.swing.GroupLayout.Alignment.TRAILING,
										javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE,
										Short.MAX_VALUE)
								.addComponent(jLabel8, javax.swing.GroupLayout.Alignment.TRAILING,
										javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE,
										Short.MAX_VALUE)
								.addComponent(jLabel10, javax.swing.GroupLayout.Alignment.TRAILING,
										javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE,
										Short.MAX_VALUE)
								.addGroup(javax.swing.GroupLayout.Alignment.TRAILING,
										pnlPanel1Layout.createSequentialGroup().addGap(0, 0, Short.MAX_VALUE)
												.addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 322,
														javax.swing.GroupLayout.PREFERRED_SIZE)))
						.addContainerGap()));
		pnlPanel1Layout.setVerticalGroup(pnlPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(pnlPanel1Layout.createSequentialGroup().addGap(19, 19, 19)
						.addGroup(pnlPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
								.addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 26,
										javax.swing.GroupLayout.PREFERRED_SIZE)
								.addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 26,
										javax.swing.GroupLayout.PREFERRED_SIZE))
						.addGroup(pnlPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
								.addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE,
										javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
								.addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE,
										javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
						.addGroup(pnlPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
								.addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 26,
										javax.swing.GroupLayout.PREFERRED_SIZE)
								.addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 26,
										javax.swing.GroupLayout.PREFERRED_SIZE))
						.addGap(38, 38, 38)
						.addGroup(pnlPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
								.addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 26,
										javax.swing.GroupLayout.PREFERRED_SIZE)
								.addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 26,
										javax.swing.GroupLayout.PREFERRED_SIZE))
						.addGroup(pnlPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
								.addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE,
										javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
								.addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE,
										javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
						.addGap(0, 0, 0)
						.addGroup(pnlPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
								.addComponent(jLabel11, javax.swing.GroupLayout.DEFAULT_SIZE,
										javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
								.addComponent(jLabel12, javax.swing.GroupLayout.DEFAULT_SIZE,
										javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
						.addGap(0, 0, 0)
						.addGroup(pnlPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
								.addComponent(jLabel13, javax.swing.GroupLayout.DEFAULT_SIZE,
										javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
								.addComponent(jLabel14, javax.swing.GroupLayout.DEFAULT_SIZE,
										javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
						.addGap(0, 0, 0)
						.addGroup(pnlPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
								.addComponent(jLabel15, javax.swing.GroupLayout.DEFAULT_SIZE,
										javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
								.addComponent(jLabel16, javax.swing.GroupLayout.DEFAULT_SIZE,
										javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
						.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
						.addGroup(pnlPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
								.addComponent(cmdButton1)
								.addComponent(cmdButton2, javax.swing.GroupLayout.DEFAULT_SIZE,
										javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
								.addComponent(txtField1, javax.swing.GroupLayout.PREFERRED_SIZE,
										javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
						.addGap(18, 18, 18)));

		jLabel1.getAccessibleContext().setAccessibleName("p_name");
		jLabel2.getAccessibleContext().setAccessibleName("name");
		jLabel4.getAccessibleContext().setAccessibleName("department_name");
		jLabel6.getAccessibleContext().setAccessibleName("get_date");
		jLabel7.getAccessibleContext().setAccessibleName("p_name");
		jLabel8.getAccessibleContext().setAccessibleName("name");
		jLabel9.getAccessibleContext().setAccessibleName("p_department_name");
		jLabel10.getAccessibleContext().setAccessibleName("department_name");
		jLabel11.getAccessibleContext().setAccessibleName("p_get_gate");
		jLabel12.getAccessibleContext().setAccessibleName("get_date");
		jLabel13.getAccessibleContext().setAccessibleName("p_serial_number");
		jLabel14.getAccessibleContext().setAccessibleName("serial_number");
		jLabel15.getAccessibleContext().setAccessibleName("p_contact");
		jLabel16.getAccessibleContext().setAccessibleName("contact");
		cmdButton1.getAccessibleContext().setAccessibleName("next");
		cmdButton2.getAccessibleContext().setAccessibleName("previous");

		javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
		getContentPane().setLayout(layout);
		layout.setHorizontalGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(layout.createSequentialGroup()
						.addComponent(pnlPanel1, javax.swing.GroupLayout.PREFERRED_SIZE,
								javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
						.addGap(0, 0, 0)));
		layout.setVerticalGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addComponent(
				pnlPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE,
				javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE));

		pack();
		showPrintLabel();
		setGUIText(FixedAssets_all.get(rowIndex));
		txtField1.setText((rowIndex+1)+" / "+FixedAssets_all.size());
		//rowIndex++;
	}// </editor-fold>//GEN-END:initComponents
	
	private static frmPrintLabel myInstance;

	public static frmPrintLabel getInstance() {
	    if (myInstance == null) {
	        myInstance = new frmPrintLabel();
	    }
	    return myInstance;
	}
	
	/**
	 * @param args
	 *            the command line arguments
	 */
	/*
	 * public static void main(String args[]) { Set the Nimbus look and feel
	 * //<editor-fold defaultstate="collapsed" desc=
	 * " Look and feel setting code (optional) "> If Nimbus (introduced in Java
	 * SE 6) is not available, stay with the default look and feel. For details
	 * see
	 * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
	 * 
	 * try { for (javax.swing.UIManager.LookAndFeelInfo info :
	 * javax.swing.UIManager.getInstalledLookAndFeels()) { if
	 * ("Nimbus".equals(info.getName())) {
	 * javax.swing.UIManager.setLookAndFeel(info.getClassName()); break; } } }
	 * catch (ClassNotFoundException ex) {
	 * java.util.logging.Logger.getLogger(frmPrintLabel.class.getName()).log(
	 * java.util.logging.Level.SEVERE, null, ex); } catch
	 * (InstantiationException ex) {
	 * java.util.logging.Logger.getLogger(frmPrintLabel.class.getName()).log(
	 * java.util.logging.Level.SEVERE, null, ex); } catch
	 * (IllegalAccessException ex) {
	 * java.util.logging.Logger.getLogger(frmPrintLabel.class.getName()).log(
	 * java.util.logging.Level.SEVERE, null, ex); } catch
	 * (javax.swing.UnsupportedLookAndFeelException ex) {
	 * java.util.logging.Logger.getLogger(frmPrintLabel.class.getName()).log(
	 * java.util.logging.Level.SEVERE, null, ex); } //</editor-fold>
	 * 
	 * Create and display the form java.awt.EventQueue.invokeLater(new
	 * Runnable() { public void run() { new frmPrintLabel().setVisible(true); }
	 * }); }
	 */

	public void showPrintLabel() {
		try{
			DBManager db = new DBManager();
			
			try {
				
				ResultSet rs;
				rs = db.getRecord("Select * from Fixed_Assets");
				while (rs.next()) {
					FixedAssets fa = new FixedAssets();
					fa.setGet_year(rs.getInt(3));
					fa.setGet_month(rs.getInt(4));
					fa.setGet_day(rs.getInt(5));
					fa.setName(rs.getString(6));
					FixedAssets_all.add(fa);
					//setGUIText();
				}
	
			} catch (SQLException ex) {
				ex.printStackTrace();
			} finally{
				db.close();
			}
		} catch (Exception e) {
			e.printStackTrace();
		}
	}
	public void setGUIText(FixedAssets fa) {
		jLabel2.setText(fa.getName());
		jLabel6.setText(String.valueOf(fa.getGet_year())+ " " +fa.getGet_month()+ " " + fa.getGet_day());
		jLabel8.setText(fa.getName());
		jLabel12.setText(String.valueOf(fa.getGet_year())+ " " +fa.getGet_month()+ " " + fa.getGet_day());
	}


	
	
	// Variables declaration - do not modify//GEN-BEGIN:variables
	private javax.swing.JButton cmdButton1;
	private javax.swing.JButton cmdButton2;
	private javax.swing.JLabel jLabel1;
	private javax.swing.JLabel jLabel10;
	private javax.swing.JLabel jLabel11;
	private javax.swing.JLabel jLabel12;
	private javax.swing.JLabel jLabel13;
	private javax.swing.JLabel jLabel14;
	private javax.swing.JLabel jLabel15;
	private javax.swing.JLabel jLabel16;
	private javax.swing.JLabel jLabel2;
	private javax.swing.JLabel jLabel3;
	private javax.swing.JLabel jLabel4;
	private javax.swing.JLabel jLabel5;
	private javax.swing.JLabel jLabel6;
	private javax.swing.JLabel jLabel7;
	private javax.swing.JLabel jLabel8;
	private javax.swing.JLabel jLabel9;
	private javax.swing.JPanel pnlPanel1;
	private javax.swing.JTextField txtField1;
	
	private List<FixedAssets> FixedAssets_all = new ArrayList<FixedAssets>();
	private int rowIndex = 0;
	// End of variables declaration//GEN-END:variables
}
